Workaround runtime problem on Windows
RuntimeError: The current Numpy installation
('C:\\Users\\rjollos\\Documents\\Workspace\\otonexus
\\e4990a\\venv\\lib\\site-packages\\numpy\\__init__.py')
fails to pass a sanity check due to a bug in the windows
runtime. See this issue for more information:
https://tinyurl.com/y3dm3h86